import type { Metadata } from 'next'
import Link from 'next/link'
import { Users, ShoppingCart, Table , House} from 'lucide-react'
import { ReactNode } from 'react'
import classNames from 'classnames'
import { usePathname } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

function NavBar({ currentPath }: { currentPath: string }) {
  const navItems = [
    { label: 'Dashboard', href: '/', icon: House },
    { label: 'User', href: '/user', icon: Users },
    { label: 'Order', href: '/order', icon: ShoppingCart },
    { label: 'Table', href: '/table', icon: Table },
  ]

  return (
    <nav className="bg-white border-b border-gray-200 shadow-sm sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 flex justify-around">
        {navItems.map(({ label, href, icon: Icon }) => {
          const isActive = currentPath.startsWith(href)
          return (
            <Link
              key={label}
              href={href}
              className={classNames(
                'flex flex-col items-center px-3 py-1 text-sm font-medium',
                isActive ? 'text-blue-600' : 'text-gray-500 hover:text-blue-500'
              )}
            >
              <Icon size={20} className="mb-1" />
              {label}
            </Link>
          )
        })}
      </div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  const currentPath = typeof window !== 'undefined' ? window.location.pathname : '' // fallback para SSR

  return (
    <html lang="en">
      <body className="bg-gray-50 text-black">
        <NavBar currentPath={currentPath} />
        {children}
      </body>
    </html>
  )
}
